/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.group19.easySql.ui.internal.EasySqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EasySqlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EasySqlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EasySqlActivator activator = EasySqlActivator.getInstance();
		return activator != null ? activator.getInjector(EasySqlActivator.UK_AC_KCL_INF_GROUP19_EASYSQL_EASYSQL) : null;
	}

}
