/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage;
import uk.ac.kcl.inf.group19.easySql.easySql.MultiType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multi Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultiTypeImpl extends MinimalEObjectImpl.Container implements MultiType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasySqlPackage.Literals.MULTI_TYPE;
  }

} //MultiTypeImpl
