/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage;
import uk.ac.kcl.inf.group19.easySql.easySql.QueryStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Query Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class QueryStatementImpl extends StatementImpl implements QueryStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QueryStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EasySqlPackage.Literals.QUERY_STATEMENT;
  }

} //QueryStatementImpl
