/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.Insert#getInsert_data <em>Insert data</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends ManipulateStatement
{
  /**
   * Returns the value of the '<em><b>Insert data</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.group19.easySql.easySql.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insert data</em>' containment reference list.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getInsert_Insert_data()
   * @model containment="true"
   * @generated
   */
  EList<Value> getInsert_data();

} // Insert
