/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi Equation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getEquationLeft <em>Equation Left</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getOperator <em>Operator</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getEquationRight <em>Equation Right</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getMultiEquation()
 * @model
 * @generated
 */
public interface MultiEquation extends EObject
{
  /**
   * Returns the value of the '<em><b>Equation Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equation Left</em>' containment reference.
   * @see #setEquationLeft(Vvalue)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getMultiEquation_EquationLeft()
   * @model containment="true"
   * @generated
   */
  Vvalue getEquationLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getEquationLeft <em>Equation Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equation Left</em>' containment reference.
   * @see #getEquationLeft()
   * @generated
   */
  void setEquationLeft(Vvalue value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.group19.easySql.easySql.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.Operator
   * @see #setOperator(Operator)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getMultiEquation_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Equation Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equation Right</em>' containment reference.
   * @see #setEquationRight(Vvalue)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getMultiEquation_EquationRight()
   * @model containment="true"
   * @generated
   */
  Vvalue getEquationRight();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.MultiEquation#getEquationRight <em>Equation Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equation Right</em>' containment reference.
   * @see #getEquationRight()
   * @generated
   */
  void setEquationRight(Vvalue value);

} // MultiEquation
