/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nested Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getNtable <em>Ntable</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getNattributes <em>Nattributes</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getNattributes1 <em>Nattributes1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getSubselectquery <em>Subselectquery</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getNestedQuery()
 * @model
 * @generated
 */
public interface NestedQuery extends QueryStatement
{
  /**
   * Returns the value of the '<em><b>Ntable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ntable</em>' reference.
   * @see #setNtable(TableDeclaration)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getNestedQuery_Ntable()
   * @model
   * @generated
   */
  TableDeclaration getNtable();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getNtable <em>Ntable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ntable</em>' reference.
   * @see #getNtable()
   * @generated
   */
  void setNtable(TableDeclaration value);

  /**
   * Returns the value of the '<em><b>Nattributes</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.group19.easySql.easySql.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nattributes</em>' containment reference list.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getNestedQuery_Nattributes()
   * @model containment="true"
   * @generated
   */
  EList<Value> getNattributes();

  /**
   * Returns the value of the '<em><b>Nattributes1</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.group19.easySql.easySql.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nattributes1</em>' containment reference list.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getNestedQuery_Nattributes1()
   * @model containment="true"
   * @generated
   */
  EList<Value> getNattributes1();

  /**
   * Returns the value of the '<em><b>Subselectquery</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subselectquery</em>' reference.
   * @see #setSubselectquery(SingleSelectDeclaration)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getNestedQuery_Subselectquery()
   * @model
   * @generated
   */
  SingleSelectDeclaration getSubselectquery();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.NestedQuery#getSubselectquery <em>Subselectquery</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subselectquery</em>' reference.
   * @see #getSubselectquery()
   * @generated
   */
  void setSubselectquery(SingleSelectDeclaration value);

} // NestedQuery
