/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getQueryStatement()
 * @model
 * @generated
 */
public interface QueryStatement extends Statement
{
} // QueryStatement
