/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.StrLiteral#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getStrLiteral()
 * @model
 * @generated
 */
public interface StrLiteral extends MultiType
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getStrLiteral_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.StrLiteral#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

} // StrLiteral
