/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.easySql;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vvalue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.Vvalue#getTable <em>Table</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.Vvalue#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.group19.easySql.easySql.Vvalue#getSeparation <em>Separation</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getVvalue()
 * @model
 * @generated
 */
public interface Vvalue extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(TableDeclaration)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getVvalue_Table()
   * @model
   * @generated
   */
  TableDeclaration getTable();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.Vvalue#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(TableDeclaration value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference.
   * @see #setAttribute(MultiType)
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getVvalue_Attribute()
   * @model containment="true"
   * @generated
   */
  MultiType getAttribute();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.group19.easySql.easySql.Vvalue#getAttribute <em>Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' containment reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(MultiType value);

  /**
   * Returns the value of the '<em><b>Separation</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Separation</em>' attribute list.
   * @see uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage#getVvalue_Separation()
   * @model unique="false"
   * @generated
   */
  EList<String> getSeparation();

} // Vvalue
