/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.group19.easySql.ui.internal.EasySqlActivator;

public class EasySqlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EasySqlActivator.getInstance().getInjector("uk.ac.kcl.inf.group19.easySql.EasySql");
	}

}
