/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.group19.easySql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEasySqlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.kcl.inf.group19.easySql.easySql.EasySqlPackage.eINSTANCE);
		return result;
	}
}
