/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.group19.easySql


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EasySqlRuntimeModule extends AbstractEasySqlRuntimeModule {
}
