/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.group19.easySql


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EasySqlStandaloneSetup extends EasySqlStandaloneSetupGenerated {

	def static void doSetup() {
		new EasySqlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
